version: "3.9"
services:

# Zabbix 3 & 4 MySQL

  mysql57-zabbix:
    image: "mysql:5.7"
    environment:
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "zabbix_pwd"

# Zabbix 3 environment

  zabbix3-server-mysql:
    image: "zabbix/zabbix-server-mysql:ubuntu-3.4-latest"
    ports:
      - "10053:10051"
    environment:
      DB_SERVER_HOST: "mysql57-zabbix"
      MYSQL_DATABASE: "zabbix3"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "zabbix_pwd"

  zabbix3-web:
    image: "zabbix/zabbix-web-nginx-mysql:ubuntu-3.4-latest"
    ports:
      - "8083:80"
    environment:
      ZBX_SERVER_HOST: "zabbix3-server-mysql"
      DB_SERVER_HOST: "mysql57-zabbix"
      MYSQL_DATABASE: "zabbix3"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "zabbix_pwd"

# Zabbix 4 environment

  zabbix4-server-mysql:
    image: "zabbix/zabbix-server-mysql:ubuntu-4.4-latest"
    ports:
      - "10054:10051"
    environment:
      DB_SERVER_HOST: "mysql57-zabbix"
      MYSQL_DATABASE: "zabbix4"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "zabbix_pwd"

  zabbix4-web:
    image: "zabbix/zabbix-web-nginx-mysql:ubuntu-4.4-latest"
    ports:
      - "8084:8080"
    environment:
      ZBX_SERVER_HOST: "zabbix4-server-mysql"
      DB_SERVER_HOST: "mysql57-zabbix"
      MYSQL_DATABASE: "zabbix4"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"

# Zabbix 5 environment

  mysql8-zabbix:
    image: "mysql:8.0"
    environment:
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "zabbix_pwd"

  zabbix5-server-mysql:
    image: "zabbix/zabbix-server-mysql:ubuntu-latest"
    ports:
      - "10055:10051"
    environment:
      DB_SERVER_HOST: "mysql8-zabbix"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "zabbix_pwd"

  zabbix5-web:
    image: "zabbix/zabbix-web-nginx-mysql:ubuntu-latest"
    ports:
      - "8085:8080"
    environment:
      ZBX_SERVER_HOST: "zabbix5-server-mysql"
      DB_SERVER_HOST: "mysql8-zabbix"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "zabbix_pwd"

  pszabbix:
    # image: "mcr.microsoft.com/powershell:latest"
    build:
      context: .devcontainer
      dockerfile: .\pscoredev.Dockerfile
    environment:
      # DEV_ZABBIX_HOST: zabbix3-web
      # DEV_ZABBIX_API_URL: "http://zabbix3-web:8080/api_jsonrpc.php"
      # DEV_ZABBIX_HOST: zabbix4-web
      # DEV_ZABBIX_API_URL: "http://zabbix4-web:8080/api_jsonrpc.php"
      DEV_ZABBIX_HOST: zabbix5-web
      DEV_ZABBIX_API_URL: "http://zabbix5-web:8080/api_jsonrpc.php"
    command: /bin/sh -c "while sleep 1000; do :; done"
